# Generated by Django 3.2 on 2021-05-29 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20210512_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='TradeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cryptoID', models.CharField(max_length=40)),
                ('amount', models.FloatField(default=0)),
                ('tradeDate', models.DateTimeField()),
                ('tradeType', models.CharField(max_length=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='database.user')),
            ],
        ),
    ]
