# Generated by Django 3.2 on 2021-05-29 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_tradehistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradehistory',
            name='currentPrice',
            field=models.FloatField(default=0),
        ),
    ]
